### ISSUE TITLE
textport spam

### ISSUE THREAD

**Issue by sunsp1der** [picturesbyrobots/td-completes-me#3]
I'm getting some textport spam: 
> {'search_term': 'dat_SearchReplaceExt__td_15204_49.py', 'search_method': 'editing_file'}
repeated a bunch of times.

I think it's from line 423 of td_completes_me_ext.

If you use the function "debug" instead of "print" when you're sending debug info to the textport, it'll tell you what DAT and line the print came from. Super useful when you're just throwing stuff in to test, because if you forget to take it out you know exactly where the spam is coming from.

**Comment by picturesbyrobots** [comment]
hmmm...which build are you using? I generally try to keep all of my print statements out of the release builds.  Build v0_3_1 should have those removed. 

though good to know about the debug line. I was unaware that function existed! 

I've noticed in the past that the TOX format makes publishing shareable components pretty difficult as I can't run any of the usual diffing tools version control tools that I would use on a pure python project(diff, cherrypick, e.t.c.)  However, at the same time I don't want to have to ship components to folks with external dependencies because then they'd have to deal with relative path nightmares when importing toxes into their projects.

**Comment by sunsp1der** [comment]
build/0_1_0/td_completes_me_v1_0_0

We are working on a properly diffable file format. I agree, the unreadable binaries are troublesome for this kind of stuff.
